version: '3.8'
services:
droppy:
container_name: droppy
image: silverwind/droppy
ports:
- ${PORT}:8989
volumes:
- ${CONFIG_DIR}:/config
- ${DATA_FILES_DIR}:/files
environment:
- UID=1001
- GID=1001
- TZ=Asia/Seoul
security_opt:
- no-new-privileges:true
restart: unless-stopped



# # .env
# PORT=
# CONFIG_DIR
# DATA_FILES_DIR
