version: "3"

networks:
  gitea_net:
    external: false

services:
  gitea:
    image: gitea/gitea:latest # 또는 특정 버전 명시 (예: gitea/gitea:1.21)
    container_name: gitea
    environment:
      - USER_UID=1000 # 서버의 사용자 UID (id -u 명령으로 확인)
      - USER_GID=1000 # 서버의 사용자 GID (id -g 명령으로 확인)
      # - GITEA__database__DB_TYPE=mysql # MySQL/MariaDB 사용 시
      # - GITEA__database__HOST=db:3306
      # - GITEA__database__NAME=gitea
      # - GITEA__database__USER=gitea
      # - GITEA__database__PASSWD=your_gitea_db_password
      - GITEA__database__DB_TYPE=sqlite3 # SQLite 사용 시 (간단한 설정)
      - TZ=Asia/Seoul # 시간대 설정
    restart: always
    networks:
      - gitea_net
    volumes:
      - ./gitea_data:/data # Gitea 데이터 저장 경로 (호스트와 매핑)
      # - /etc/timezone:/etc/timezone:ro # 호스트 시간대 사용 (옵션)
      # - /etc/localtime:/etc/localtime:ro # 호스트 시간대 사용 (옵션)
    ports:
      - "3000:3000" # 웹 인터페이스 포트 (호스트:컨테이너)
      - "2222:22"   # Git SSH 포트 (호스트:컨테이너, 서버의 SSH 기본 포트 22와 충돌 방지)
    # depends_on: # 데이터베이스를 별도 컨테이너로 운영 시
    #   - db

  # MySQL/MariaDB 데이터베이스 컨테이너 (선택 사항, SQLite 대신 사용 시)
  # db:
  #   image: mysql:8
  #   container_name: gitea_db
  #   restart: always
  #   environment:
  #     - MYSQL_ROOT_PASSWORD=your_mysql_root_password
  #     - MYSQL_DATABASE=gitea
  #     - MYSQL_USER=gitea
  #     - MYSQL_PASSWORD=your_gitea_db_password
  #   networks:
  #     - gitea_net
  #   volumes:
  #     - ./mysql_data:/var/lib/mysql