# Use root/example as user/password credentials
version: '3.1'

services:
  rdb:
    image: mariadb
    restart: always
    container_name: ${MARIADB_CONTAINER_NAME}
    environment:
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MARIADB_DATABASE}
      MYSQL_USER: ${MARIADB_USER}
      MYSQL_PASSWORD: ${MARIADB_PASSWORD}
      MYSQL_ALLOW_EMPTY_PASSWORD: "false"
    ports:
      - "${MARIADB_PORT}:3306"
    volumes:
      - "${MARIADB_LIB_DIR}:/var/lib/mysql"
    networks:
      mariadb_network:
        ipv4_address: ${MARIADB_INTERNAL_STATIC_IP}
    healthcheck:
      test: mysqladmin ping -h 127.0.0.1 -u $$MYSQL_USER --password=$$MYSQL_PASSWORD
      interval: 30s
      timeout: 10s
      retries: 3

  backup:
    build:
      context: .
      dockerfile: Dockerfile-backup
    container_name: ${MARIADB_CONTAINER_NAME}-backup
    restart: always
    tty: true
    volumes:
      - "${MARIADB_BACKUP_DIR}:/backup"
    environment:
      MYSQL_HOST: rdb
    networks:
      - mariadb_network
    depends_on:
      - rdb

networks:
  mariadb_network:
    driver: bridge
    ipam:
      config:
        - subnet: ${MARIADB_NETWORK_SUBNET}


# # Environment 
# MARIADB_CONTAINER_NAME=
# MARIADB_ROOT_PASSWORD=
# MARIADB_DATABASE=
# MARIADB_USER=
# MARIADB_PASSWORD=
# MARIADB_PORT=
# MARIADB_LIB_DIR=
# MARIADB_BACKUP_DIR=
# MARIADB_NETWORK_SUBNET=
# MARIADB_INTERNAL_STATIC_IP=


# # EXAMPLE OF ENVIRONMENT
# MARIADB_ROOT_PASSWORD=password
# MARIADB_DATABASE=emotion
# MARIADB_USER=user
# MARIADB_PASSWORD=password
# MARIADB_PORT=3306
# MARIADB_LIB_DIR=/user/directory/lib
# MARIADB_BACKUP_DIR=/user/directory/backup
# MARIADB_INTERNAL_STATIC_IP=172.20.0.10
# MARIADB_NETWORK_SUBNET=172.20.0.0/24

# # 환경 변수 설명
# MARIADB_CONTAINER_NAME: MariaDB 컨테이너 이름
# MARIADB_ROOT_PASSWORD: 루트 비밀번호
# MARIADB_DATABASE: 초기 데이터베이스 이름
# MARIADB_USER: 기본 사용자 이름
# MARIADB_PASSWORD: 기본 사용자 비밀번호
# MARIADB_PORT: 호스트에 노출할 포트
# MARIADB_LIB_DIR: 데이터베이스 파일 저장 경로
# MARIADB_BACKUP_DIR: 백업 파일 저장 경로
# MARIADB_INTERNAL_STATIC_IP: MariaDB 컨테이너의 고정 IP
# MARIADB_NETWORK_SUBNET: 네트워크 서브넷 (예: 172.20.0.0/16)


  adminer:
    image: adminer
    restart: always
    ports:
      - 3090:8080
