version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: unless-stopped
    ports:
      - "27018:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${username}
      MONGO_INITDB_ROOT_PASSWORD: ${password}
    volumes:
      - ../init/mongo-init.js:/docker-entrypoint-initdb.d/init.js
      - ../data/init-keyfile.sh:/docker-entrypoint-initdb.d/init-keyfile.sh:ro
      - mongodata:/data/db
    command: ["--replSet", "rs0", "--bind_ip_all", "--keyFile", "/etc/mongo/mongo-keyfile"]

volumes:
  mongodata:
    driver: local
