services:
  n8n:
    image: n8nio/n8n:latest
    ports:
      - "15678:5678"
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=${username}
      - N8N_BASIC_AUTH_PASSWORD=${password}
      - N8N_HOST=localhost
      - WEBHOOK_TUNNEL_URL=http://localhost:5678/
      - N8N_DATA_FOLDER=/tmp
    networks:
      - nodove-net

volumes:
  n8n_data:
    driver: local

networks:
  nodove-net:
    external: true
