version: "3.2"
services:
  picoshare:
    image: mtlynch/picoshare
    environment:
      - PORT=4001
      - PS_SHARED_SECRET=${PICO_SHARE_PASSWORD}
      - TZ=Asia/Seoul  # 한국 시간대 설정
    ports:
      - 4001:4001
    command: -db /data/store.db
    volumes:
      - ${DATA_DIR}:/data
    restart: unless-stopped  # 컨테이너 자동 재시작 설정
    healthcheck:  # 헬스체크 추가
      test: ["CMD", "curl", "-f", "http://localhost:4001"]
      interval: 1m
      timeout: 10s
      retries: 3
      start_period: 30s
    logging:  # 로그 설정
      options:
        max-size: "10m"
        max-file: "3"

--------------
.env
--------------
PICO_SHARE_PASSWORD=
DATA_DIR=
