version: "3.8"

services:
  db:
    image: postgres:15-alpine
    container_name: supabase_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${SUPABASE_DB_NAME:-supabase}
      POSTGRES_USER: ${SUPABASE_DB_USER:-supabase_admin}
      POSTGRES_PASSWORD: ${SUPABASE_DB_PASSWORD}
    volumes:
      - supabase_db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432" # Expose for direct access if needed
    networks:
      - nodove-net
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $$POSTGRES_USER -d $$POSTGRES_DB"]
      interval: 10s
      timeout: 5s
      retries: 5

  rest:
    image: postgrest/postgrest:v11.0.1
    container_name: supabase_rest
    restart: unless-stopped
    environment:
      PGRST_DB_URI: postgresql://${SUPABASE_DB_USER:-supabase_admin}:${SUPABASE_DB_PASSWORD}@db:5432/${SUPABASE_DB_NAME:-supabase}
      PGRST_DB_SCHEMA: public
      PGRST_DB_ANON_ROLE: anon
    ports:
      - "3000:3000" # PostgREST API port
    depends_on:
      db:
        condition: service_healthy
    networks:
      - nodove-net

volumes:
  supabase_db_data:
    driver: local

networks:
  nodove-net:
    external: true

# .env file example:
# SUPABASE_DB_NAME=supabase
# SUPABASE_DB_USER=supabase_admin
# SUPABASE_DB_PASSWORD=your_strong_password
