version: '3.8'

services:
  sourcebot:
    image: ghcr.io/sourcebot-dev/sourcebot:latest
    container_name: sourcebot
    ports:
      - "3333:3333"
    volumes:
      - .:/data
    environment:
      - CONFIG_PATH=/data/config.json
      - GITHUB_TOKEN=${GITHUB_TOKEN}
      - OPENROUTER_API_KEY=${OPENROUTER_API_KEY}
      - GEMINI_API_KEY=${GEMINI_API_KEY}
    env_file:
      - .env
    restart: unless-stopped
    pull_policy: always
