services:
  dev-flutter:
    build:
      context: ..
      dockerfile: Dockerfile/dev/Dev_Flutter.Dockerfile
    container_name: dev-flutter
    ports:
      - "8080:8080"
      - "9100:9100"
      - "5000:5000"
    volumes:
      - type: bind
        source: ../workspace
        target: /work
      - flutter-pub-cache:/home/flutter/.pub-cache
      - android-licenses:/opt/android-sdk/licenses
      - android-avd:/home/flutter/.android
      - gradle-cache:/home/flutter/.gradle
    environment:
      - DISPLAY
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  flutter-pub-cache:
  android-licenses:
  android-avd:
  gradle-cache:
