services:
  dev-go:
    build:
      context: ..
      dockerfile: Dockerfile/dev/Dev_Go.Dockerfile
    container_name: dev-go
    ports:
      - "8080:8080"
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace
      - go-mod-cache:/home/go/go/pkg
      - go-bin-cache:/home/go/go/bin
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  go-mod-cache:
  go-bin-cache:
