services:
  dev-python:
    build:
      context: ..
      dockerfile: Dockerfile/dev/Dev_Python.Dockerfile
    container_name: dev-python
    ports:
      - "8888:8888"
      - "6006:6006"
    volumes:
      - type: bind
        source: ../workspace
        target: /workspace
      - pip-cache:/home/python/.cache/pip
      - jupyter-data:/home/python/.local/share/jupyter
    tty: true
    stdin_open: true
    restart: unless-stopped

volumes:
  pip-cache:
  jupyter-data:
